### ISSUE TITLE
Reprovision Reborn v0.8.1 can't install apps from filza

### ISSUE THREAD

**Issue by luv-letter117** [sohsatoh/ReProvision-Reborn#11]
**Describe the bug**

  Reprovision Reborn can't install apps from filza

**To Reproduce**

1. Go to filza.
2. Long tap on apps, click open with App.
3. Scroll to Reprovision and click it.
4. Always show loading on the screen.

**Expected behavior**

**Screenshots**
![7FECA3D0-77BC-49F7-BAF6-BD224B7D3ACB](https://user-images.githubusercontent.com/22892413/136302203-5a08486d-133b-4be3-a0d6-f26e0f4d83e0.png)

**Device (please complete the following information):**
 - iOS Version 14.3
- Device  XS

**Additional context**

(Please do not delete lines in bold)

**Comment by sohsatoh** [comment]
Which ipa file do you want to install?
I have never faced that issue.

**Comment by luv-letter117** [comment]
> Which ipa file do you want to install?
> I have never faced that issue.

u0

**Comment by luv-letter117** [comment]
v0.6.2 is fine, but v0.7.0 and v0.8.1 not work

**Comment by sohsatoh** [comment]
From a comment on Reddit:

> What I did: revoked all certs from ReProvision, then signed out, then removed u0 and ReProvision. After that, installed it again and added u0 ipa from + button inside ReProvision. Rebooted, accepted dev from Settings and ran u0 again, it seems everything is good now.
