### ISSUE TITLE
0.8.1 caused unc0ver to be improperly signed 

### ISSUE THREAD

**Issue by robertybob** [sohsatoh/ReProvision-Reborn#13]
**Describe the bug**

Reprovision 0.8.1 re-signed unc0ver for me for the first time, now after a crash I cannot jailbreak again.  
  
I used 0.6 before and it worked fine.

**To Reproduce**
2. Tap on '....'

Try and jailbreak. It doesn’t work. 

**Expected behavior**

To be able to jailbreak 

**Screenshots**
![0BAE6422-1B95-40D9-897D-298744F6FF3F](https://user-images.githubusercontent.com/2610395/136672639-5f46d27a-5219-42b8-90aa-e101c1497bed.png)

![93807DD1-011C-467C-8BC2-F42C36D79732](https://user-images.githubusercontent.com/2610395/136672642-0abc8c59-e6d2-408d-b777-8efd7de0af68.png)

**Device (please complete the following information):**
 - iOS Version 14.3

- Device (e.g. iPhone, iPad, Apple TV, Apple Watch)
- 
iPhone XS

**Additional context**

(Please do not delete lines in bold)

**Comment by sohsatoh** [comment]
#11
