### ISSUE TITLE
Unc0ver jailbreaks successfully but then while booting into jailbroken state it kernel panics back into jailed state.

### ISSUE THREAD

**Issue by detfusco** [sohsatoh/ReProvision-Reborn#14]
After updating ReProvision Reborn (to 8.1.0), my iPad Pro 10.5”( iPadOS 13.5, unc0ver 5.3.1) kept kernel panicking upon rejailbreaking successfully. I had to rootfs via unc0ver which solved the problem but it was a real pain in the ass to set it up again. I also remember enabling true background signing but I don’t even know if that’s the culprit here. I have a several kernel panic logs claiming reprovision caused it. This was the first of many logs: [Panic log](https://pastebin.com/g449YFdK)
also other posts about the aformentioned kernel panic problem: [Post 1](https://www.reddit.com/r/jailbreak/comments/q4lnr0/comment/hg0ene8/?utm_source=reddit&utm_medium=web2x&context=3) ,
[Post 2](https://www.reddit.com/r/jailbreak/comments/q4xcz4/comment/hg2283q/?utm_source=reddit&utm_medium=web2x&context=3)

**Describe the bug**

**To Reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch)

**Additional context**

(Please do not delete lines in bold)

**Comment by sohsatoh** [comment]
I'm not the developer of u0, obviously.

**Comment by sohsatoh** [comment]
If I have time I will look into it, but I don't have a spare device and it may take some time.
(As I personally prefer Taurine).

**Comment by detfusco** [comment]
> I'm not the developer of u0, obviously.

I literally said unc0ver jailbreaks successfully it’s the reprovision that causes kernel panics according to apple’s own analytics log. I’m not entirely sure if it’s limited to unc0ver but we’ll see that in time, I guess.

**Comment by sohsatoh** [comment]
It should be fixed in development branch.
