### ISSUE TITLE
Cannot update ReProvision Reborn on both iPad and iPhone 

### ISSUE THREAD

**Issue by andrefrpinto** [sohsatoh/ReProvision-Reborn#17]
**Describe the bug**
When trying to update ReProvision reborn from 0.7.0 to 8.0.2 on both my devices, jail broken with unc0ver, on iOS 13.5, through Zebra, I get the following pop up message: “ReProvision Reborn has issues that cannot be resolved: “com.matchstic.reprovision” conflicts with Reprovision Reborn”. My options are “Ok”, which doesn’t update the package, or “Remove from queue”, which does exactly that.

**To Reproduce**
1. Go to Zebra
2. Update the ReProvision reborn package to the latest version

**Expected behavior**
Normal update process, without errors.

**Screenshots**
![IMG_1068](https://user-images.githubusercontent.com/41691583/137185225-f89456b0-57c1-4110-a4bc-b91f3344f6e6.png)

**Device (please complete the following information):**
 - iOS Version: 13.5
- Devices: both iPad Pro 2018 and iPhone 11

**Additional context**

(Please do not delete lines in bold)

**Comment by sohsatoh** [comment]
uninstall reprovision first.
