### ISSUE TITLE
Reprovision causes env to crash

### ISSUE THREAD

**Issue by cameren2k** [sohsatoh/ReProvision-Reborn#18]
**Describe the bug**
reprovision causes env to crash multiple times

**To Reproduce**
don't exactly have a way to reproduce or what exactly causes the issue

**Expected behavior**
not crash

**Screenshots**

https://pastebin.com/ZWyzdfFY

**Device (please complete the following information):**
iOS 14.3 Xr latest taurine 
**Additional context**
nothing else to add

(Please do not delete lines in bold)

**Comment by sohsatoh** [comment]
which jb are you using?

**Comment by cameren2k** [comment]
> which jb are you using?

latest taurine, so 1.1.1

**Comment by sohsatoh** [comment]
Could you try running this on Terminal and check whether it crashes or not.

`/usr/bin/env _MSSafeMode=1 _SafeMode=1 /usr/libexec/reprovisiond`

**Comment by cameren2k** [comment]
seems to run fine; hasn't crashed![image](https://user-images.githubusercontent.com/48306344/137690259-78cadf49-7e82-4c55-a9d3-d9061b145c87.jpeg)

**Comment by cameren2k** [comment]
an update to this, i did notice you had a beta repo. i tried that version (not sure if you fixed the env crash yet or not) but it did have the same issue where it crashed exactly 25 times.

**Comment by sohsatoh** [comment]
Try restoring rootfs.

**Comment by cameren2k** [comment]
i have done this multiple times. this does not fix the issue
