### ISSUE TITLE
Can't install apps from filza on 0.8.2

### ISSUE THREAD

**Issue by luv-letter117** [sohsatoh/ReProvision-Reborn#19]
**Describe the bug**
Can't install apps from filza.

**To Reproduce**
See the video below.

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/22892413/137927568-5b0ef9f1-a725-4a08-a3ea-b4570e188dea.MP4

**Device (please complete the following information):
 - iOS Version 14.3
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch) Ipad

**Additional context**

(Please do not delete lines in bold)

**Comment by sohsatoh** [comment]
Does that happen every time (I mean, all ipa files)?

**Comment by luv-letter117** [comment]
Yes, but 0.6.2 is normal.

**Comment by sohsatoh** [comment]
i will not provide any support for ppl using cydown
