### ISSUE TITLE
Signed uncover6.2.0 not working on 0.7.0

### ISSUE THREAD

**Issue by youknow-svg** [sohsatoh/ReProvision-Reborn#3]
**Describe the bug**

When i updated to 0.7.0 and after i signed uncover, when i open uncover and try to jailbreak I received error

**To Reproduce**

1. Go to 'uncover'
2. Tap on 'jailbreak'
3. Scroll down to 'report'

**Expected behavior**

An error occurred while verifying the entitlements of our application. This build was signed improperly. Please install the build with official methods from https://uncOver.dev and try again.

**Screenshots**

**Device (please complete the following information):**
 - iOS 14.3
- Device (iphone 12)

**Additional context**

I downgraded the tweak to previous version and every thing works fine

(Please do not delete lines in bold)

**Comment by RuyeNet** [comment]
Use Reprovison Reborn v0.6.2 to solve this problem. The bug will be fixed in the next version.
More information: https://github.com/sohsatoh/ReProvision-Reborn/issues/1

**Comment by 2ndMessiah** [comment]
The dev should push 0.8 beta or at least notify that 0.7 is a bootlegged version that will generate wrong entitlement.

**Comment by sohsatoh** [comment]
@2ndMessiah 
> The dev **should** ~

I owe you nothing. It's free software. If you want to complain, build it yourself. If you can't even build it, don't complain. I'll do what I want.
