### ISSUE TITLE
ReProvision-Reborn  0.7.0 breaks unc0ver 6.1.2 

### ISSUE THREAD

**Issue by EdgeXS** [sohsatoh/ReProvision-Reborn#5]
**Describe the bug**
After signing with ReProvision-Reborn  .70 unc0ver 6.1.2 can not complete.

**To Reproduce**
1. upgraded from reprovision 0.6.2 to 0.7.0.
2. signed unc0ver 6.1.2 with reprovision 0.7.0.
3. rebooted phone
4. attempted to use 6.1.2 to jailbreak phone
5. error message from unc0ver when attempting to jailbreak.  "An error occurred while verifying the entitlements of our application.  This build was signed improperly. Please install the build with official methods from https://unc0ver.de and try again."
6. downgraded to reprovision 0.6.2
7. issue did not occur.

**Expected behavior**
To sign the unc0ver.IPA correctly as it did in reprovision 0.6.2.

**Screenshots**
Attached screenshot is of the error message I received after signing with reprovision 0.7.0 from unc0ver 6.1.2

**Device (please complete the following information):**
 - iOS Version
- Device (e.g. iPhone, iPad, Apple TV, Apple Watch)

**Additional context**

(Please do not delete lines in bold
![error](https://user-images.githubusercontent.com/48872441/133891544-3800969a-7e7f-47d5-aa3d-c805e1b15d35.png)
)

**Comment by sohsatoh** [comment]
#1
